# Generated by Django 4.1.7 on 2023-03-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_complete',
        ),
    ]
