# Generated by Django 4.1.7 on 2023-03-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_result_score_in_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
